# Generated by Django 5.2.14 on 2026-05-29 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sucursal', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=500)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursales',
                'ordering': ['id_supermercado', 'nombre_sucursal'],
            },
        ),
        migrations.CreateModel(
            name='Supermercado',
            fields=[
                ('id_supermercado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('sitio_web', models.URLField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Supermercado',
                'verbose_name_plural': 'Supermercados',
                'db_table': 'supermercados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria_padre', models.ForeignKey(blank=True, db_column='id_categoria_padre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='src.categoria')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro')], max_length=10)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='src.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['nombre', 'marca'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('precio_registrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='src.producto')),
                ('id_sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='src.sucursal')),
            ],
            options={
                'verbose_name': 'Historial de Precio',
                'verbose_name_plural': 'Historial de Precios',
                'db_table': 'historial_precios',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddField(
            model_name='sucursal',
            name='id_supermercado',
            field=models.ForeignKey(db_column='id_supermercado', on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='src.supermercado'),
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id_precio', models.AutoField(primary_key=True, serialize=False)),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('en_oferta', models.BooleanField(default=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='src.producto')),
                ('id_sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='src.sucursal')),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
                'db_table': 'precios',
                'ordering': ['precio_actual'],
                'unique_together': {('id_producto', 'id_sucursal')},
            },
        ),
    ]
